_target_: src.models.components.language_decoder.LanguageDecoder

tokenizer: ${data.tokenizer}

config:
  _target_: transformers.Speech2Text2Config
  
  d_model: 256
  decoder_ffn_dim: 1536
  decoder_layers: 7
  decoder_attention_heads: 4
  dropout: 0.1
  
  layerdrop: 0.05

