defaults:
  - _self_
  - net: sign_language_net

_target_: src.models.sign_language_module.SignLanguageLitModule

net:
  encoder:
    config:
      freeze_feature_extractor: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-6 # our batch size is nowhere comparable to that of the Wav2Vec2 authors...

