defaults:
  - _self_
  - net: decoder/language_decoder

_target_: src.models.sign_language_pretraining.SignLanguagePretrainingLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2e-5

