defaults:
  - _self_
  - net: decoder/language_decoder

_target_: src.models.langdecoder_pretraining_module.LangDecoderPretrainingModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 2e-5

