_target_: src.models.sign_language_module.SignLanguageLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-5
#  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.sign_language_net.SignLanguageNet
  tokenizer: ${data.tokenizer}

# compile model for faster training with pytorch 2.0
compile: False
