defaults:
  - _self_
  - net: decoder/language_decoder

_target_: src.models.sign_language_module.SignLanguageLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 4e-5

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# compile model for faster training with pytorch 2.0
compile: False
