_target_: src.models.sign_language_module.SignLanguageLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 3e-5

scheduler: null

net:
  _target_: src.models.components.sign_language_net.SignLanguageNet
  tokenizer: ${data.tokenizer}

# compile model for faster training with pytorch 2.0
compile: False
