defaults:
  - _self_
  - net: custom_spatiotemporal_pretraining

_target_: src.models.spatiotemporal_pretraining_module.SpatiotemporalPretrainingModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 5e-5