defaults:
  - _self_
  - net: custom_spatiotemporal_pretraining

_target_: src.models.spatiotemporal_pretraining_module.SpatiotemporalPretrainingModule

net:
  config:
    freeze_feature_extractor: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 6e-6 # everything more destabilizes the training at our current batch size.