defaults:
  - _self_
  - net: custom_videomae_pretraining

_target_: src.models.videomae_pretraining_module.VideoMAEPretrainingModule


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.5e-5