_target_: src.models.components.spatiotemporal_encoder.SpatiotemporalEncoder

config:
  _target_: src.models.components.spatiotemporal_encoder.SpatiotemporalEncoderConfig

  freeze_feature_extractor: false