# @package _global_

# overfits to 3 batches

defaults:
  - default

trainer:
  max_epochs: 10
  overfit_batches: 3
  accelerator: gpu


data:
  num_workers: 0
  pin_memory: True


# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
