# @package _global_

# overfits to 3 batches

defaults:
  - default

trainer:
  max_epochs: 10
  overfit_batches: 5
  limit_val_batches: 0
  check_val_every_n_epoch: 1000

  accelerator: gpu

model:
  optimizer:
    lr: 1e-4
  scheduler: null

data:
  num_workers: 6
  batch_size: 2
  pin_memory: True

test: False

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
