# @package _global_

# overfits to 3 batches

defaults:
  - default

trainer:
  max_epochs: 100
  overfit_batches: 10
  accelerator: gpu
  limit_val_batches: 0
  check_val_every_n_epoch: 1000

optimizer:
  lr: 2e-4

scheduler: null

data:
  num_workers: 6
  pin_memory: True

test: False

# model ckpt and early stopping need to be disabled during overfitting
callbacks: null
