name: Release on tag

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to all tags

jobs:
  get-ocir-repository-test:
    runs-on: ubuntu-22.04
    name: Push to OCIR Repository
    env:
      OCI_CLI_USER: ${{ env.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ env.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ env.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ env.OCI_CLI_REGION }}
    steps:
      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: master-thesis-dev
          compartment: ${{ env.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build images
        id: build-image
        env:
          IMAGE_NAME: ${{ steps.get-ocir-repository.outputs.repo_path }}/training
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            .

      - name: Tag and push a container image
        id: tag-and-push-image
        env:
          IMAGE_NAME: ${{ steps.get-ocir-repository.outputs.repo_path }}/training
        run: |
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:${{ github.ref_name }}"