name: Release on tag

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*' # Push events to all tags

jobs:
  get-ocir-repository-test:
    runs-on: ubuntu-latest
    name: Push to OCIR Repository
    env:
      OCI_CLI_USER: ${{ vars.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ vars.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ vars.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ vars.OCI_CLI_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Oracle Cloud Container Registry
        run: |
          docker login -u "${{ secrets.OCI_USER_OCID }}/oracleidentitycloudservice/${{ secrets.OCI_USERNAME }}" -p "${{ secrets.OCI_AUTH_TOKEN }}" ${OCI_REGION}.ocir.io

      - name: Build images
        id: build-image
        env:
          IMAGE_NAME: ${{vars.OCI_CLI_REGION}}.ocir.io/${{ secrets.OCI_TENANCY_NAME }}/master-thesis-dev/training
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            .

      - name: Tag and push a container image
        id: tag-and-push-image
        env:
          IMAGE_NAME: ${{ vars.OCI_IMAGE }}/training
        run: |
          docker push "$IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:${{ github.ref_name }}"