defaults:
  - _self_

_target_: src.models.components.videomae_with_decoder.CustomVideoMAEForPreTraining
config:
  _target_: transformers.VideoMAEConfig
  attention_probs_dropout_prob: 0.0,
  decoder_hidden_size: 384
  decoder_intermediate_size: 1536
  decoder_num_attention_heads: 6
  decoder_num_hidden_layers: 4
  hidden_act: gelu
  hidden_dropout_prob: 0.0
  hidden_size: 768
  image_size: 224
  initializer_range: 0.02
  intermediate_size: 3072
  layer_norm_eps: 1e-12
  norm_pix_loss: true
  num_attention_heads: 12
  num_channels: 3
  num_frames: 80
  num_hidden_layers: 12
  patch_size: 16
  qkv_bias: true
  torch_dtype: float32
  tubelet_size: 2
  use_mean_pooling: false