defaults:
  - _self_

_target_: src.models.components.spatiotemporal_encoder.SpatiotemporalEncoderForPreTraining
config:
  _target_: src.models.components.spatiotemporal_encoder.SpatiotemporalEncoderConfig
  freeze_feature_extractor: False